name: PR Validation (CI)
on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'infra/**'
      - '.github/workflows/**'
jobs:
  validate-backend:
    name: Build & Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile and Build Application
        run: |
          cd backend
          ./mvnw clean package -DskipTests

      - name: Run Automated Tests
        run: |
          cd backend
          ./mvnw test

  validate-infra:
    name: Lint Infrastructure Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: infra/docker/Dockerfile
          ignore: DL3008

      - name: Lint Github Workflows
        run: |
          bash <(curl -shttps://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint